name: Continuous Integration

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t kmenzyk/docker-react --file Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true kmenzyk/docker-react yarn run test
      
  deploy:
    
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v1
      
      - name: Generate deployment package
        run: zip deploy.zip *
      
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v3
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: eu-west-1
          application_name: docker-react
          environment_name: DockerReact-env
          version_label: ${{github.sha}}
          deployment_package: deploy.zip
